name: Deploy Next.js to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Next.js
      - name: Build Next.js
        run: npm run build

      # 5. Prepare deployment folder
      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r .next deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp -r public deploy/

      # 6. Deploy to Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: azure-demoo        # your Azure Web App name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy
